#!/bin/bash
This is file iacta as presented in the question.
The file is used to display th third lines of its contents only.
No other lines that is four onwards is to be diaplayed. 
Kindly take note.
